# Generated by Django 4.2.1 on 2023-05-10 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teas', '0002_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=200)),
                ('frequency', models.CharField(max_length=200)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teas.customer')),
                ('tea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teas.tea')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_subscription',
            field=models.ManyToManyField(through='teas.Subscription', to='teas.tea'),
        ),
        migrations.AddField(
            model_name='tea',
            name='tea_subscription',
            field=models.ManyToManyField(through='teas.Subscription', to='teas.customer'),
        ),
    ]
